### ISSUE TITLE
Left key behavior has changed since v0.9.9

### ISSUE THREAD

**Issue by jamadam** [trol73/mucommander#145]
Hi.

On file lists I used to hit the left key once a time to go to parent directory but since v0.9.9 I have to hit the key twice a time because the cursor move to parent via the top element ".."

Is it possible to achieve the old behavior by preference?

**Comment by trol73** [comment]
Hi,

Yes, that's possible.
Since 0.9.9 added two new actions - NavigateLeft and NavigateRight
See this issue: https://github.com/trol73/mucommander/issues/126

You can assign left arrow to GoToParent action (instead of NavigateLeft action).

p.s. For someone new navigation seems more comfortable. But personally I also prefer the old left arrow behavior.

**Comment by jamadam** [comment]
Thanks. I found the new short cut for me was delete.
I should be used to it since I'm a big fun of default settings :)

**Comment by dstd** [comment]
Excuse me, please, for posting into the closed issue, but is there a similar solution to revive a time-honoured behavior of RIGHT key? Or at least force them to avoid the jump if the selection is set on a file.

**Comment by trol73** [comment]
Yes, you can associate Right key to the "Open" action
