### ISSUE TITLE
[feature request] Gradle support

### ISSUE THREAD

**Issue by gnh1201** [trol73/mucommander#149]
Gradle is good build automation for workspace of IDE (eclipse, intelij, etc...)

Also, since muCommander 0.9.1, It support Gradle environment.

**Comment by trol73** [comment]
I personally use ant to run trolCommander and to build release jar.
But if someone wants to add gradle-scripts, then welcome :)

**Comment by dstd** [comment]
I needed to debug the app, but simple open and run in IDEA didn't work for me (probably due to unsyncs in non-Ant configs). 

So I made a simple Gradle script for the app, just to quickly inflate IDEA's environment (actually the bunch of dependencies) from scratch, without any goals beyond the app debugging. Maybe it will be helpful for someone too.

```gradle
// build.gradle

plugins {
    id 'java'
    id 'application'
}

repositories {
    jcenter()
}

dependencies {
    implementation fileTree(include: ['*.jar', '**/*.jar'], dir: 'lib/runtime')
}

sourceSets {
    main {
        java.srcDirs = ['src/main']
        resources.srcDirs = ['res/runtime']
    }
}

mainClassName = 'com.mucommander.TrolCommander'
```
