### ISSUE TITLE
Android device not showing up

### ISSUE THREAD

**Issue by mardukbp** [trol73/mucommander#155]
`adb devices` shows my device (Galaxy Tab S2 running Android 7.0) and I can connect to it using [aafm](https://github.com/sole/aafm). However, I cannot find it anywhere in trolcommander nor do I get any debug message related to ADB.

**Comment by trol73** [comment]
try to create file
~/Library/Preferences/trolCommander/env.properties
with one line
`ANDROID_HOME=/Users/username/Library/Android/sdk/`
and specify android SDK location

**Comment by mardukbp** [comment]
I'm on Ubuntu 16.04. I created `$HOME/.trolcommander/env.properties` with the contents

```
ANDROID_HOME=/usr/lib/android-sdk
```

I verified that inside that directory there is the directory platform-tools that contains the adb executable. Still I cannot see the device.

**Comment by mardukbp** [comment]
Never mind. I figured it out. I did not need to create any file. I only needed to know how to use the program ;) I just clicked on the menu to the left of the path and there I found Android.

Sorry for the fuss.

**Comment by LeeBinder** [comment]
@trol73 : hello Oleg, are you still around in here? I did not want to open a new issue for my question because it more or less fits in here.

I can connect to my android 7.1.1 phone (rooted via Magisk) with trolCommander for Mac both builds, 2016-12-29 and 2018-10-24 nightly (trolcommander.jar and trolcommander-macosx.jar). I have "shell" enabled in Magisk Superuser options. I do see the root level folders and files, but when I click into /data, the folder content is not listed (folder stays empty).

Latest ADB Platform Tools downloaded from https://www.droidviews.com/download-latest-adb-and-fastboot-sdk-platform-tools-win-mac-linux and extracted to ~/Library/Android/sdk/ - adb binary executed and version verified to be latest v.1.0.41.

On my phone I should be seeing superuser requests executed for "shell" as I do when I connect via adbLink (it has a horrible file manager, though, but it does list files and folders in /data, however slow) and adbfs for Finder, but I don't.

I already tried several things to no avail:
- creating env.properties as you describe above
- run trolCommander with root privs
- 'restart adb server as local user.command':
```
#!/bin/bash
adb kill-server
adb start-server
echo
adb devices
```
- 'restart adb server as su.command':
```
#!/bin/bash
sudo adb kill-server
sudo adb start-server
echo
adb devices
```
When I boot into TWRP, trolCommander gets one step further and does list content of /data, but not of /data/data

It seems trolCommander does not execute adb with full root privs?

**Comment by trol73** [comment]
Hello,
trolCommander does file navigation without using 'sudo' command.
I have a similar problem with the OnePlus (not root-ed) device . The '/mnt' folder is 'empty' because I don't have  permissions to view it. But this directory contains all "interesting" subdirectories, for example
adb://586f64b5/mnt/sdcard/Music
adb://586f64b5/mnt/sdcard/DCIM
adb://586f64b5/mnt/sdcard/Download
To solve the problem, I just bookmarked them (latest versions support nested bookmarks). 

Now I have such a menu:
![](https://psv4.userapi.com/c848220/u17445537/docs/d6/e7d6e2f7959c/Screenshot_2019-05-21_at_09_33_24.png?extra=QTeRcDX-uOtKxGMZdp0tQuoF-Rf9JZD4GH1e3858xqYz7AsXJao9HozxRQP2QK6FIYs2BvYYcjWcUQ7mS0A8UuMG4LZ-TFM47-5-Emo4NFhd1fCQuQ0CzWgSmmqofNStvNvJX4dgfBuP11sYxy-6dt-L)

**Comment by LeeBinder** [comment]
Hi Oleg. The nested bookmarks feature you implemented is neat but bookmarking does not solve it in this case because folders like /data/data remain inaccessible even with bookmarks edited with the desired paths.

The folders you use are all also accessible via regular MTP. ADB's powers lies in its root access capability, which MTP lacks completely. I just found out last nite that it's easy to implement su into adb shell calls (even without the necessity of enabling/ installing insecure root adbd on the phone for complete 'adb root'). Via Terminal on one's computer:
```
adb shell
su
```
or one liner (might not work in all cases):
`adb shell "su"`

If you also have access to a rooted android phone, you can test yourself:
- in Magisk Superuser settings, toggle 'Shell' to 'On' and 'Superuser Access' to 'Apps and ADB'
- run above two liner -> the prompt from "jackpot2lte:/ **$**" (=user build) should turn to "jackpot2lte:/ **#**" (=engineer build), and you should be able to successfully run
```
cd data/data
ls 
```
or one liner (again might not work in all cases):
`adb shell "su -c ls /data/data" `
:)

If su for ADB is not enabled in Android, such folders will still simply remain blank. In other words, there is no downside to just adding the "su" to the part of trolCommander's code with the 'adb shell' call.

I'll gladly serve as a guinea pig for test runs, if you have any free time for compiling an initial adb su edition🥇 

PS: just for the record: [full 'adb root' how-2](https://stackoverflow.com/questions/25477424/adb-shell-su-works-but-adb-root-does-not/25490518#25490518), as possible 2nd stage adb ramp-up for your app in the future.

**Comment by LeeBinder** [comment]
@trol73 Hey Oleg, by now it's coming along rather nicely here 👍  I learned over at XDA that even "shell su" requires an (insecure) adbd on the phone so that adb switches to root when starting on the computer OS for seamless access to /system/... and /data/data/...

After installing [Chainfire's adbd insecure](https://forum.xda-developers.com/showthread.php?t=1687590) (unfortunately discontinued and outdated) on my phone, adb via your trolCommander is working pretty nicely and swiftly. The old app is using an old adbd binary from Android 5.0 (sdk 21) - my ROM is 7.1.1 (sdk 25), oh well.. (no success yet in creating a root capable adbd from my current ROM's boot.img YET .. )

**Question:** I'm wondering: do you utilize a method with code similar to
```
 if (checkRoot())
      rootShell = " shell su -c ";
  else
      rootShell = " shell ";
```
**?**

**Comment by trol73** [comment]
Hi, 
Good news, thanks!
Regarding "su" - trolCommander uses the library "se.vidstige.jadb" to work with adb. I looked at the code, it seems that it will not work so easy to add there "su" command.
And what if you try to add permissions to directories (since the device is still rooted)?

**Comment by LeeBinder** [comment]
Right - your java based commander needs a java "flavor" of adb .. that's why it does behave differently than adbLink file manager.

change directories perms: I'd rather not esp. to data/data because that would be a *huge* security hole.

Question: are you using the [latest v1.1.0 of the se.vidstige.jadb library](https://github.com/vidstige/jadb/releases) from May 19, 2018 in your nightly, and if not, could you update it with it 🥇 ?

**Comment by trol73** [comment]
Hmm, I thought that a rooted device is in itself a huge security hole.. :)

I do not use the latest version of the library.  I once copied it and made changes to the code. if I remember correctly, in addition to cosmetic refactoring, I made corrections. After that I tried to synchronize changes from there (but, as far as I remember, they were usually more cosmetic).

**Comment by LeeBinder** [comment]
LOL yes, in a way. But I still feel better and thus "safer" when my phone does what **_I_** want and not what Google, Samsung and all the app devs want .. ;)

OK (vidstige.jadb library). BTW, do you have a change log of the differences between your stable and nightly?

**Comment by trol73** [comment]
Google, Samsung and any other Android software already has read (and probably write) access to folders in /data/ :) Access is denied only for adb user. 

I have no differences logs. I did not transfer changes from jadb somewhere for the last year. But I don't see any changes in jadb for file browsing with su..

**Comment by LeeBinder** [comment]
hm, still the same with your latest nightly (thank you for keeping trolCommander alive!) + my new Nokia 6.1 with Android 11 LineageOS 18.1. I guess it's just the way it is.
