### ISSUE TITLE
Apple M1, New releases

### ISSUE THREAD

**Issue by trx222** [trol73/mucommander#175]
Hi Oleg, do you had the chance to check whats needed to get the trolCommander running on M1 Macs?

Also I wonder about very old releases - there are sometimes new commits, do you plan to build a new release?

best regards, Tony

**Comment by trol73** [comment]
Hi,
I can't say anything yet about M1 since I don't have one :)
Regarding new releases - yes, I am planning them in the future. And the latest nightly build can always be downloaded from my [GoogleDrive](https://drive.google.com/drive/folders/0BwgV75Rd8itZUnYyaVNERUdsZHM#list).
In the future, I plan to transfer nightly builds to the web page and implement auto-update.

**Comment by trx222** [comment]
Great, it works. I just installed a jre and everything is fine with the nightly.
