### ISSUE TITLE
Integrate new features into official repo

### ISSUE THREAD

**Issue by VladRassokhin** [trol73/mucommander#55]
Recently mucommander migrated to github, so it would be nice to integrate features from your fork into [official repo](https://github.com/mucommander/mucommander).

**Comment by trol73** [comment]
Unfortunately I didn't get any response from muCommander team. Looks like that this project is dead and I will develop my fork separately

**Comment by ahadas** [comment]
Hi, how did you try to reach us? I didn't get anything.. we encourage people to fork so they will be able to customize and improve muCommander for their own needs, but if the work can be useful for others (and it seems so), I would say that joint work on one project is the better option.

muCommander is not dead :) we were doing things 'behind the scenes' for quite some time and planning the future of the project. If you want to talk, I'm almost always available on muCommander's IRC channel or you can send me an email, or you can post patches on gerrithub :) 

Either way, you did a nice job here and if you decide to keep developing it separately, I would love to see you rebasing or cherry-pick the next improvements/features that will be merged to muCommander in the future.

**Comment by trol73** [comment]
Hi,
I tried to connect wit you via facebook (because I didn't find any your email and other contacts). I also wrote several times to Maxence before to start my branch.

I completely agree that it would be better to develop a single muCommander together. Now I've made a huge amount of code changes (bug fixes, code refactoring, compile warnings elimination, performance optimisation etc.) and I see no easy way to merge all to muCommander. However, some features can be easily transferred (find files, hex-viewer, improved image viewer, calculator etc.).

**Comment by ahadas** [comment]
Hi,
I'm sorry, I just saw your message on facebook, I missed it somehow (probably because it is in the "messages from others" section which I didn't check)..

There will be a price for merging changes from your branch to the official branch of course, but I think that in the longer term, it worth it. Not all the changes should be merged at-once, and I'm sure that some of the changes could be merged much easier after we'll do some of the changes we plan to do (I hope that we'll be able to publish version 0.9.1 soon and then implement them).

I think the way to go is to have a chat/call with Maxence & Nicolas to discuss about it. I'll try to organize something and I'll talk with you on facebook.
