### ISSUE TITLE
Poor icon quality on OS X

### ISSUE THREAD

**Issue by alexey-lysiuk** [trol73/mucommander#84]
Starting from 7ee409b the quality of file icons on OS X became much worse.
This screenshot was grabbed on release 0.9.5, the last commit before 7ee409b:
<img width="179" alt="good" src="https://cloud.githubusercontent.com/assets/777125/8637181/499f818a-288d-11e5-9de2-b9c2cd6e155e.png">
And this is from 7ee409b:
<img width="211" alt="bad" src="https://cloud.githubusercontent.com/assets/777125/8637180/497bd3ca-288d-11e5-8bb7-b8d9e660b281.png">
Apparently, something is wrong with icons returned by Quaqua.
Images were taken on 10.10.4 running JVM 1.8.0_45. **Use system file icons** options is set to **Always**.

**Comment by trol73** [comment]
The main advantage of the Quaqua library - quality images for sizes larger than 16 x 16.
This can be especially actual for the Retina. When used JFileChooser instead of Quaqua then quality of icons with sizes about 200 - 300% was terrible. 
I think that the best solution here - write new JNI code for icon extraction. As alternative we can use JFileChooser for getting icons with size 16 x 16

**Comment by alexey-lysiuk** [comment]
I took the screenshots above from Retina display. The display scale was 200% and icons were not scaled, but they are definitely not looking good.
Version 0.9.5 (and previous I suppose) doesn't have this issue. Thus a new code for icon extraction is an overkill for this purpose. I think it will be enough to handle the mentioned case by a workaround of some sort.

**Comment by trol73** [comment]
Fixed. Retina icons are now supported
